#ifndef LAB3_ERRORS_H
#define LAB3_ERRORS_H

#include "iostream"

enum Errors
{
    NULL_POINTER_ERROR = 1,
    WRONG_PATH_ERROR = 2,
    WRONG_TRAVERSAL_INPUT_ERROR = 3,
    ZERO_SIZE_ERROR = 3,
    INVALID_STRING_ERROR = 4,
    /*INDEX_OUR_OF_RANGE_ERROR = 4,
    NOT_EQUAL_SIZES_ERROR = 5,
    WRONG_SIZE_ERROR = 6,*/
};

#endif
